/* 
 * AdventureWorksLT
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


namespace AdventureWorksLT.Service.Client
{
    /// <inheritdoc />
    /// <summary>
    /// <see cref="T:AdventureWorksLT.Service.Client.GlobalConfiguration" /> provides a compile-time extension point for globally configuring
    /// API Clients.
    /// </summary>
    /// <remarks>
    /// A customized implementation via partial class may reside in another file and may
    /// be excluded from automatic generation via a .swagger-codegen-ignore file.
    /// </remarks>
    public class GlobalConfiguration : Configuration
    {

    }
}