/* 
 * AdventureWorksLT
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AdventureWorksLT.Service.Api;
using AdventureWorksLT.Service.Model;
using AdventureWorksLT.Service.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AdventureWorksLT.Service.Test
{
    /// <summary>
    ///  Class for testing Product
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProductTests
    {
        // TODO uncomment below to declare an instance variable for Product
        //private Product instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Product
            //instance = new Product();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Product
        /// </summary>
        [Test]
        public void ProductInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Product
            //Assert.IsInstanceOfType<Product> (instance, "variable 'instance' is a Product");
        }


        /// <summary>
        /// Test the property 'ProductID'
        /// </summary>
        [Test]
        public void ProductIDTest()
        {
            // TODO unit test for the property 'ProductID'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ProductNumber'
        /// </summary>
        [Test]
        public void ProductNumberTest()
        {
            // TODO unit test for the property 'ProductNumber'
        }
        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Test]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }
        /// <summary>
        /// Test the property 'StandardCost'
        /// </summary>
        [Test]
        public void StandardCostTest()
        {
            // TODO unit test for the property 'StandardCost'
        }
        /// <summary>
        /// Test the property 'ListPrice'
        /// </summary>
        [Test]
        public void ListPriceTest()
        {
            // TODO unit test for the property 'ListPrice'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Test]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
        /// <summary>
        /// Test the property 'ProductCategoryID'
        /// </summary>
        [Test]
        public void ProductCategoryIDTest()
        {
            // TODO unit test for the property 'ProductCategoryID'
        }
        /// <summary>
        /// Test the property 'ProductModelID'
        /// </summary>
        [Test]
        public void ProductModelIDTest()
        {
            // TODO unit test for the property 'ProductModelID'
        }
        /// <summary>
        /// Test the property 'SellStartDate'
        /// </summary>
        [Test]
        public void SellStartDateTest()
        {
            // TODO unit test for the property 'SellStartDate'
        }
        /// <summary>
        /// Test the property 'SellEndDate'
        /// </summary>
        [Test]
        public void SellEndDateTest()
        {
            // TODO unit test for the property 'SellEndDate'
        }
        /// <summary>
        /// Test the property 'DiscontinuedDate'
        /// </summary>
        [Test]
        public void DiscontinuedDateTest()
        {
            // TODO unit test for the property 'DiscontinuedDate'
        }
        /// <summary>
        /// Test the property 'ThumbNailPhoto'
        /// </summary>
        [Test]
        public void ThumbNailPhotoTest()
        {
            // TODO unit test for the property 'ThumbNailPhoto'
        }
        /// <summary>
        /// Test the property 'ThumbnailPhotoFileName'
        /// </summary>
        [Test]
        public void ThumbnailPhotoFileNameTest()
        {
            // TODO unit test for the property 'ThumbnailPhotoFileName'
        }
        /// <summary>
        /// Test the property 'Rowguid'
        /// </summary>
        [Test]
        public void RowguidTest()
        {
            // TODO unit test for the property 'Rowguid'
        }
        /// <summary>
        /// Test the property 'ModifiedDate'
        /// </summary>
        [Test]
        public void ModifiedDateTest()
        {
            // TODO unit test for the property 'ModifiedDate'
        }

    }

}
