/* 
 * AdventureWorksLT
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AdventureWorksLT.Service.Api;
using AdventureWorksLT.Service.Model;
using AdventureWorksLT.Service.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AdventureWorksLT.Service.Test
{
    /// <summary>
    ///  Class for testing SalesOrderDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SalesOrderDetailTests
    {
        // TODO uncomment below to declare an instance variable for SalesOrderDetail
        //private SalesOrderDetail instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SalesOrderDetail
            //instance = new SalesOrderDetail();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SalesOrderDetail
        /// </summary>
        [Test]
        public void SalesOrderDetailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SalesOrderDetail
            //Assert.IsInstanceOfType<SalesOrderDetail> (instance, "variable 'instance' is a SalesOrderDetail");
        }


        /// <summary>
        /// Test the property 'SalesOrderID'
        /// </summary>
        [Test]
        public void SalesOrderIDTest()
        {
            // TODO unit test for the property 'SalesOrderID'
        }
        /// <summary>
        /// Test the property 'SalesOrderDetailID'
        /// </summary>
        [Test]
        public void SalesOrderDetailIDTest()
        {
            // TODO unit test for the property 'SalesOrderDetailID'
        }
        /// <summary>
        /// Test the property 'OrderQty'
        /// </summary>
        [Test]
        public void OrderQtyTest()
        {
            // TODO unit test for the property 'OrderQty'
        }
        /// <summary>
        /// Test the property 'ProductID'
        /// </summary>
        [Test]
        public void ProductIDTest()
        {
            // TODO unit test for the property 'ProductID'
        }
        /// <summary>
        /// Test the property 'UnitPrice'
        /// </summary>
        [Test]
        public void UnitPriceTest()
        {
            // TODO unit test for the property 'UnitPrice'
        }
        /// <summary>
        /// Test the property 'UnitPriceDiscount'
        /// </summary>
        [Test]
        public void UnitPriceDiscountTest()
        {
            // TODO unit test for the property 'UnitPriceDiscount'
        }
        /// <summary>
        /// Test the property 'LineTotal'
        /// </summary>
        [Test]
        public void LineTotalTest()
        {
            // TODO unit test for the property 'LineTotal'
        }
        /// <summary>
        /// Test the property 'Rowguid'
        /// </summary>
        [Test]
        public void RowguidTest()
        {
            // TODO unit test for the property 'Rowguid'
        }
        /// <summary>
        /// Test the property 'ModifiedDate'
        /// </summary>
        [Test]
        public void ModifiedDateTest()
        {
            // TODO unit test for the property 'ModifiedDate'
        }

    }

}
